print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
print ("just a test...and then some")   
